export component CenterPlayButton {
    in-out property <bool> playing;
    callback clicked;
    callback controls-moved;

    Rectangle {
        width: 100%;
        height: 100%;
        border-color: rgba(255, 255, 255, 0.45);
        border-width: 2px;
        background: rgba(0, 0, 0, 0.45);

        Path {
            width: 24px; height: 24px;
            fill: #fff;
            commands: root.playing 
                ? "M 4 0 L 9 0 L 9 24 L 4 24 Z M 15 0 L 20 0 L 20 24 L 15 24 Z" 
                : "M 4 0 L 22 12 L 4 24 Z";
            x: (parent.width - self.width) / 2 + (root.playing ? 0px : 2px);
            y: (parent.height - self.height) / 2;
        }

        TouchArea {
            moved => { root.controls-moved(); }
            clicked => { root.clicked(); }
        }
    }
}
